services:
  agent_tools_api:
    build:
      context: ./src/agent_tools_api
    env_file: .env
    ports:
      - "8080:8080"
    restart: unless-stopped

  aiocc_runner:
    build:
      context: .
      dockerfile: Dockerfile.aiocc
    env_file: .env
    depends_on:
      - agent_tools_api
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    # command: ["streamlit", "run", "app.py"] # Defined in Dockerfile
    restart: unless-stopped
